wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batchSize:
  desc: null
  value: 64
epsDecaySteps:
  desc: null
  value: 1000
epsEnd:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.9
hSize:
  desc: null
  value: 128
inSize:
  desc: null
  value: 17
lr:
  desc: null
  value: 0.001
memorySize:
  desc: null
  value: 100000
nActions:
  desc: null
  value: 8
nHidden:
  desc: null
  value: 2
tau:
  desc: null
  value: 0.001
