wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batchSize:
  desc: null
  value: 256
epsDecaySteps:
  desc: null
  value: 10000
epsEnd:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.9
hSize:
  desc: null
  value: 256
inSize:
  desc: null
  value: 23
lr:
  desc: null
  value: 0.001
memorySize:
  desc: null
  value: 1000000
nActions:
  desc: null
  value: 20
nHidden:
  desc: null
  value: 2
name:
  desc: null
  value: 5Cyl
num_random_episodes:
  desc: null
  value: 10
tau:
  desc: null
  value: 0.005
