wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
action_range:
  desc: null
  value: 0.2
actor_h_size:
  desc: null
  value: 128
actor_lr:
  desc: null
  value: 0.0001
actor_n_hidden:
  desc: null
  value: 2
alpha:
  desc: null
  value: 0.7
batch_size:
  desc: null
  value: 64
beta:
  desc: null
  value: 0.5
critic_h_size:
  desc: null
  value: 128
critic_lr:
  desc: null
  value: 0.001
critic_n_hidden:
  desc: null
  value: 4
critic_wd:
  desc: null
  value: 0.01
eps_decay:
  desc: null
  value: 0.9998
eps_end:
  desc: null
  value: 0.02
epsilon:
  desc: null
  value: 0.75
gamma:
  desc: null
  value: 0.99
mem_size:
  desc: null
  value: 1000000
tau:
  desc: null
  value: 0.001
